/**
 * VCP (Video Control Panel) Code Descriptions
 * Based on VESA MCCS Standard
 */

export const VCP_CODES: Record<number, string> = {
  // Preset Operations
  0x00: "Code Page",
  0x01: "Degauss",
  0x02: "New Control Value",
  0x03: "Soft Controls",
  
  // Image Adjustment
  0x04: "Restore Factory Defaults",
  0x05: "Restore Factory Brightness/Contrast",
  0x06: "Restore Factory Geometry",
  0x08: "Restore Factory Color Defaults",
  0x0A: "Restore Factory TV Defaults",
  0x0B: "Color Temperature Increment",
  0x0C: "Color Temperature Request",
  0x0E: "Clock",
  0x10: "Brightness",
  0x12: "Contrast",
  0x14: "Select Color Preset",
  0x16: "Red Video Gain",
  0x18: "Green Video Gain",
  0x1A: "Blue Video Gain",
  0x1C: "Focus",
  0x1E: "Auto Setup",
  0x20: "Horizontal Position",
  0x22: "Horizontal Size",
  0x24: "Horizontal Pincushion",
  0x26: "Horizontal Pincushion Balance",
  0x28: "Horizontal Convergence",
  0x2A: "Horizontal Linearity",
  0x2C: "Horizontal Linearity Balance",
  0x30: "Vertical Position",
  0x32: "Vertical Size",
  0x34: "Vertical Pincushion",
  0x36: "Vertical Pincushion Balance",
  0x38: "Vertical Convergence",
  0x3A: "Vertical Linearity",
  0x3C: "Vertical Linearity Balance",
  0x3E: "Clock Phase",
  
  // Color/Tone
  0x40: "Horizontal Parallelogram",
  0x42: "Vertical Parallelogram",
  0x44: "Horizontal Keystone",
  0x46: "Vertical Keystone",
  0x48: "Rotation",
  0x4A: "Top Corner Flare",
  0x4C: "Top Corner Hook",
  0x4E: "Bottom Corner Flare",
  0x50: "Bottom Corner Hook",
  0x52: "Horizontal Moire",
  0x54: "Vertical Moire",
  0x56: "Red Video Black Level",
  0x58: "Green Video Black Level",
  0x5A: "Blue Video Black Level",
  0x5B: "6-axis Saturation: Red",
  0x5C: "6-axis Saturation: Yellow",
  0x5D: "6-axis Saturation: Green",
  0x5E: "6-axis Hue Control",
  
  // Input/Source
  0x60: "Input Source",
  0x62: "Audio Speaker Volume",
  0x63: "Speaker Select",
  0x64: "Audio Microphone Volume",
  0x66: "Ambient Light Sensor",
  0x68: "Backlight Control",
  0x6C: "Red Video Black Level",
  0x6E: "Green Video Black Level",
  0x70: "Blue Video Black Level",
  0x72: "Gamma",
  0x74: "LUT Size",
  0x76: "Single Point LUT Operation",
  0x78: "Block LUT Operation",
  
  // Display Control
  0x7C: "Adjust Zoom",
  0x7E: "Trapezoid",
  0x80: "Horizontal Mirror (Flip)",
  0x82: "Vertical Mirror (Flip)",
  0x84: "Display Scaling",
  0x86: "Sharpness",
  0x87: "Velocity Scan Modulation",
  0x88: "Color Saturation",
  0x8A: "TV Channel Up/Down",
  0x8C: "TV Sharpness",
  0x8D: "Audio Mute/Screen Blank",
  0x8E: "TV Contrast",
  0x90: "Hue",
  0x92: "TV Black Level/Luminance",
  0x94: "Window Position TL_X",
  0x96: "Window Position TL_Y",
  0x98: "Window Position BR_X",
  0x9A: "Window Position BR_Y",
  0x9B: "Window Background",
  0x9C: "6-axis Hue: Red",
  0x9D: "6-axis Hue: Yellow",
  0x9E: "6-axis Hue: Green",
  0x9F: "6-axis Hue: Cyan",
  0xA0: "6-axis Hue: Blue",
  0xA1: "6-axis Hue: Magenta",
  0xA2: "Auto Setup On/Off",
  0xA4: "Window Mask Control",
  0xA5: "Window Select",
  0xA6: "Window Size",
  0xA8: "Window Transparency",
  
  // Power/Energy
  0xAA: "Screen Orientation",
  0xAC: "Horizontal Frequency",
  0xAE: "Vertical Frequency",
  0xB0: "Settings",
  0xB2: "Gray Scale Expansion",
  0xB4: "Source Timing Mode",
  0xB6: "Display Technology Type",
  0xB7: "Monitor Status",
  0xB8: "Packet Count",
  0xB9: "Monitor X Origin",
  0xBA: "Monitor Y Origin",
  0xBB: "Header Error Count",
  0xBC: "Body CRC Error Count",
  0xBD: "Client ID",
  0xBE: "Link Control",
  
  // Miscellaneous Functions
  0xC0: "Display Usage Time",
  0xC2: "Display Descriptor Length",
  0xC3: "Transmit Display Descriptor",
  0xC4: "Enable Display of 'Display Descriptor'",
  0xC6: "Application Enable Key",
  0xC8: "Display Controller Type",
  0xC9: "Display Firmware Level",
  0xCA: "OSD/Button Control",
  0xCC: "OSD Language",
  0xCD: "Status Indicators",
  0xCE: "Auxiliary Display Size",
  0xD0: "Output Select",
  0xD2: "Asset Tag",
  0xD4: "Stereo Video Mode",
  0xD6: "Power Mode",
  0xD7: "Auxiliary Power Output",
  0xD8: "Scan Mode",
  0xDA: "Image Mode",
  0xDC: "Display Application",
  0xDE: "Scratch Pad",
  0xDF: "VCP Version",
  
  // Manufacturer Specific (0xE0-0xFF)
  0xE0: "Manufacturer Specific - OSD Button",
  0xE1: "Manufacturer Specific - Power LED",
  0xE2: "Manufacturer Specific - Overdrive",
};

export function getVcpCodeName(code: number): string {
  return VCP_CODES[code] || "Unknown/Manufacturer Specific";
}


